### ISSUE TITLE
Issue setting up DEV VM

### ISSUE THREAD

**Issue by KirankumarAmbati** [relativitydev/relativity-dev-vm#77]
I am trying to setup DEV VM as per the documentation but facing an error.

OS: Windows 10

Error:

![image](https://user-images.githubusercontent.com/9110567/72868369-d83a8280-3d07-11ea-9411-a57e7107cac3.png)

My settings:

![image](https://user-images.githubusercontent.com/9110567/72868399-ee484300-3d07-11ea-9843-1adea7ee38f1.png)

Tried googling for solution. Most answers are suggesting that there can be a configuration error with Network Adapter but mine seems okay. Please need your help. Thank you!

**Comment by KirankumarAmbati** [comment]
**CC:** @calimetikcura

**Comment by calimetikcura** [comment]
@KirankumarAmbati are you still having this issue?

My guess is that this issue could be because of some hardware might not be available like CPU Cores, RAM or network adapter.

Please post your issue on DevHelp as this is our preferred way of addressing any DevVm issues you may have. This is the link for the DevVM category on DevHelp where you can post your issue - https://devhelp.relativity.com/c/tools-testing-download-and-tutorials/devvm

**Comment by KirankumarAmbati** [comment]
@calimetikcura 

Thank you for the reply! It might be an issue with Hardware. It started working after a restart.

Earlier I wasn't aware of DevHelp. So raised issue here. I started using DevHelp and we had already talked earlier today :)

Thank you once again. Closing the issue!
